### ISSUE TITLE
ROS compile error

### ISSUE THREAD

**Issue by BRNKR** [plusk01/aruco_localization#1]
Hey,

i have some issues with compiling your code. Ive installed aruco like you wrote in your README. but i get this error with catkin_make:
https://pastebin.com/8rcaqt8Q

The FindAruco.cmake is at its correct position ;)

**Comment by plusk01** [comment]
Hmm.. it can't seem to find the installed library for some reason. What are the versions of everything you are running? (Ubuntu, ROS, ArUco)

Did you change anything in the `CMakeLists.txt`? And is it `FindAruco.cmake` or `Findaruco.cmake` at `/usr/local/lib/cmake/` ?

**Comment by BRNKR** [comment]
It is `Findaruco.cmake`. I am running Ubuntu 16.04 with ROS Kinetic and ArUco 2.0.19.

**Comment by plusk01** [comment]
With your same setup (Ubuntu 16.04, ROS Kinetic, ArUco 2.0.19) and following these instructions others (including myself) have successfully installed this package.
